### ISSUE TITLE
Restrict Full Heal

### ISSUE THREAD

**Issue by carlmylo** [moistbois/Moist-Liberation-APR#15]
### Short Summary
Currently anyone can access the Full Heal option from the Player Actions Menu. This should be put on a cooldown. Another idea is that it could be restricted to medics only.

### Description
Anyone can freely spam the Full Heal option while at a FOB and this is goofy. Ideally full heal should only be able to be used every 5 or so minutes. It already has a limit to check whether or not it can be used while enemies are around which is a good start but I feel it's still a bit too cheesy.

If we want to be masochists, we could restrict it so that only medics can mass heal everyone at FOBs but this would have the massive downside of solo players not being able to heal during logistics downtime unless they're playing a medic.

## Challenges
- How can we repurpose the HALO and Mobile Respawn cooldowns and use them in this context?
- It seems the [[Halo jump]](https://github.com/moistbois/Moist-Liberation-APR/blob/main/Missionframework/scripts/client/spawn/do_halo.sqf#L5-L7) script does the cooldown a bit more efficiently?
- We can also check the [[Mobile respawn]](https://github.com/moistbois/Moist-Liberation-APR/blob/main/Missionframework/scripts/client/spawn/redeploy_manager.sqf#L214-L230) cooldown script.
- The variable for whether or not a player is a "real" medic is `ace_medical_medicClass`. We could check for this variable if we really want to make healing a painful experience. I don't think we should go through with it but it is an idea I had at one point.

**Comment by doxus** [comment]
Closed by #19
