### ISSUE TITLE
Persistent vehicle damage, fuel, and ammo

### ISSUE THREAD

**Issue by carlmylo** [moistbois/Moist-Liberation-APR#4]
## Current State:
The campaign saves class, position, direction (both horizontal and vertical), and inventory (added in)

When a vehicle is damaged, runs out a fuel, or runs out of ammo, a simple server restart will fix everything. This makes workbenches, fuel bladders/pumps, and ammo containers/trucks useless the mission stays booted for an extended period of time. This, however, is not ideal as the performance will degrade overtime and the server needs to be shut down for mission updates.

## Suggested change:
We add `_damage`, `_fuel`, and `_ammo` to the save function.

These should be the right parameters for this. The question is where to add them?

The save manager was previously edited to add persistent cargo on `L411` in [`Missionframework/scripts/server/game/save_manager.sqf`](https://github.com/moistbois/Moist-Liberation-APR/blob/mmsp/Missionframework/scripts/server/game/save_manager.sqf#L411)

After that, it moves to [L426 to L472](https://github.com/moistbois/Moist-Liberation-APR/blob/mmsp/Missionframework/scripts/server/game/save_manager.sqf#L426-L472).

At least that's what it looks like.

## Challenges:
- This will require extensive testing as the save mechanism is a critical function for obvious reasons.
- Are we sure that `_damage`, `_fuel`, and `_ammo` are the right parameters?
- Will this work on a dedicated server?

**Comment by doxus** [comment]
So far I've figured out how to save/load:
- main fuel state
- cargo fuel (requires ACE)
- specific hit points damage (annoying to load)

Need to work on ammo - this will probably require saving array of present magazines in the vehicle? Or at least in the turrets?

**Comment by doxus** [comment]
Ammo is ignored for now since it's more annoying to do than damage - cant be bothered to work on that now
