### ISSUE TITLE
Redundant variant

### ISSUE THREAD

**Issue by TiredSloth69** [moistbois/Moist-Liberation-APR#6]
https://github.com/moistbois/Moist-Liberation-APR/blob/7ed0ef195003794e2dc8d1b7cf66c9ce4b75bdd9/Missionframework/presets/players/lingor_resistance.sqf#L140C1-L140C92

Same loadout as the other AH-1G, might have different variant of rockets but that's fixable with ace pylons.

Suggesting to swap it for the M195 variant which has one pylon swapped for the vulcan cannon which you can't add on the normal version of the cobra. Should be:
vn_b_air_ah1g_08

**Comment by carlmylo** [comment]
https://github.com/moistbois/Moist-Liberation-APR/commit/a9334a131db0112f7702d19e88c37098e1356b45
