### ISSUE TITLE
Ace Cargo Capacity Investigation

### ISSUE THREAD

**Issue by TiredSloth69** [moistbois/Moist-Liberation-APR#7]
### Is your feature request related to a problem? Please describe:

SOG vehicles do not have adjusted ace cargo values and just share the same stock value regardless of being a scout helicopter, heavy lift helicopter, truck or otherwise.
### Describe the solution you'd like:

Adjust the values for vehicles primarily used for logistics to increase efficiency to a more tolerable or believeable level.(I.e. transport trucks, chinook, choctaw, cayuse et cetera)

Alternatively look into adjusting the integrated loading system for KP liberation for some of these vehicles to make heavy transports able to carry more than 3 crates. Looking at the chinook I think it should be able to carry 4, could maybe adjust it to that or able to carry two stacks for a max of 8, though talking with Carl this seems to be a more involved process to tweak than what the ace cargo seems to be which would also be something that lets you add or remove capacity from vehicles that might have too little or too much(I.e. a light vehicle like the cayuse helicopter probably shouldn't be able to load a pallet)
### Additional context:

https://ace3.acemod.org/wiki/framework/cargo-framework.html

**Comment by doxus** [comment]
I'll have a look into how compat mods work - because those don't create new object class, but somehow extend the old one, right?

**Comment by TiredSloth69** [comment]
From what I understood from Carl it ought to work in the same way as how you changed the crates for igla launchers to be interactable with ace.
So I presume it's just a specific call to adjust the ace values from the defaults of specified items.

https://github.com/moistbois/moistbois-factions/blob/main/Lingor%201980s/blufor/autogen.hpp#L88-L99

**Comment by doxus** [comment]
With the crate we needed a separate object that has specific items inside. For the vehicles i'd like to avoid having to duplicate each one as "our own". 
I _think_ compat mods somehow extend an original object class with extra properties, without creating a separate object that is the same with extra ace properties or whatever
